# Задание 1

In [2]:
import numpy as np

In [92]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [93]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [94]:
a.mean

<function ndarray.mean>

In [95]:
mean_a = np.mean(a, 0)

In [96]:
mean_a

array([2. , 8.4])

# Задание 2

In [97]:
a_centered = a - mean_a 

In [98]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 3

In [106]:
m = a_centered[0:, :1].copy()
b = a_centered[0:, 1:2].copy()  
a_centered_sp = np.sum(m * b) / 4
a_centered_sp

2.0

# Задание 4

In [109]:
n = np.cov(np.transpose(a))
n

array([[1. , 2. ],
       [2. , 4.3]])

In [110]:
n[0,1]

2.0